# Generated by Django 5.1.2 on 2024-10-18 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="guest_can_skip",
            new_name="votes_to_skip",
        ),
    ]
